default:
  SECRET_KEY: 'qw+8hgmzk2@e46j&1kp&hopol+u!n#b#ex_aa6+3i$es(0vbqu'
  DEBUG: true
  ALLOWED_HOSTS: []

heroku:
  DEBUG: false
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - repatik.herokuapp.com

development:
  DEBUG: true
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost